package net.suncaper.userprovider.mapper;

import java.util.List;
import net.suncaper.userprovider.domain.Permission;
import net.suncaper.userprovider.domain.PermissionExample;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper extends PermissionMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    long countByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    List<Permission> selectByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByPrimaryKey(Permission record);
}