package net.suncaper.userprovider.mapper;

import java.util.List;
import net.suncaper.userprovider.domain.RolePermissionExample;
import net.suncaper.userprovider.domain.RolePermissionKey;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insertSelective(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    List<RolePermissionKey> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role_permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExample(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);
}