package net.suncaper.userprovider.mapper;

import java.util.List;
import net.suncaper.userprovider.domain.Role;
import net.suncaper.userprovider.domain.RoleExample;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByPrimaryKey(Role record);
}