package net.suncaper.userprovider.mapper;

import java.util.List;
import net.suncaper.userprovider.domain.User;
import net.suncaper.userprovider.domain.UserExample;
import org.apache.ibatis.annotations.Param;

public interface UserMapper extends UserMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByPrimaryKey(User record);
}