package net.suncaper.userprovider.mapper;

import java.util.List;
import net.suncaper.userprovider.domain.UserRoleExample;
import net.suncaper.userprovider.domain.UserRoleKey;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    long countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int deleteByPrimaryKey(UserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insert(UserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int insertSelective(UserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    List<UserRoleKey> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserRoleKey record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_user_role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    int updateByExample(@Param("record") UserRoleKey record, @Param("example") UserRoleExample example);
}