package net.suncaper.userprovider.domain;

public class Permission extends PermissionExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_permission.id
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_permission.permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_permission.display_name
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_permission.category
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_permission.url
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_permission.id
     *
     * @return the value of pt_permission.id
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_permission.id
     *
     * @param id the value for pt_permission.id
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_permission.permission
     *
     * @return the value of pt_permission.permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_permission.permission
     *
     * @param permission the value for pt_permission.permission
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_permission.display_name
     *
     * @return the value of pt_permission.display_name
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_permission.display_name
     *
     * @param displayName the value for pt_permission.display_name
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_permission.category
     *
     * @return the value of pt_permission.category
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_permission.category
     *
     * @param category the value for pt_permission.category
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_permission.url
     *
     * @return the value of pt_permission.url
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_permission.url
     *
     * @param url the value for pt_permission.url
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}