package net.suncaper.userprovider.domain;

public class Role extends RoleExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_role.id
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_role.role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_role.display_name
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    private String displayName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_role.id
     *
     * @return the value of pt_role.id
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_role.id
     *
     * @param id the value for pt_role.id
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_role.role
     *
     * @return the value of pt_role.role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_role.role
     *
     * @param role the value for pt_role.role
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_role.display_name
     *
     * @return the value of pt_role.display_name
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_role.display_name
     *
     * @param displayName the value for pt_role.display_name
     *
     * @mbg.generated Mon Dec 23 14:46:51 CST 2019
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }
}